// Action types for UI
export const ADD_BOOK_DIALOG_OPEN = 'ADD_BOOK_DIALOG_OPEN';
export const ADD_BOOK_DIALOG_CLOSE = 'ADD_BOOK_DIALOG_CLOSE';
export const ADD_BOOK_DIALOG_FORM = 'ADD_BOOK_DIALOG_FORM';
export const UPDATE_BOOK_DIALOG_FORM = 'UPDATE_BOOK_DIALOG_FORM';

